# Settings to disable shadows for windows
shadow = false;

# Fading animations settings
fading = true;
fade-delta = 10;
fade-out-step = 0.10;
fade-in-step = 0.10;
no-fading-openclose = false;

# Window opening animations settings
animations = true;
animation-for-open-window = "fade";
animation-for-open-window-time = 50;

# Window type specific settings
wintypes:
{
  tooltip = { fade = true; shadow = false; };  # Settings for tooltips
  dock = { shadow = false; };  # Settings for dock windows
  dnd = { shadow = false; };   # Settings for drag-and-drop windows
};

# Opacity settings for inactive and active windows
inactive-opacity = 1.0;
active-opacity = 1.0;
detect-client-opacity = true;

# Choosing the rendering backend
backend = "xrender";

# Additional backend settings
backend = "glx";
vsync = true;
