#################################
#           Shadows            #
#################################
# Отключить тени для окон
shadow = false;

#################################
#          Fading               #
#################################
# Включить анимацию исчезания окон
fading = true;
# Время исчезания окон в миллисекундах
fade-delta = 10;
# Время исчезания окон при закрытии
fade-out-step = 0.10;
# Время появления окон
fade-in-step = 0.10;
# Фейдить только override-redirect окна
no-fading-openclose = false;

#################################
#          Animations           #
#################################
# Включить анимацию открытия окон
animations = true;
# Настройки анимации
animation-for-open-window = "fade";
animation-for-open-window-time = 50;

#################################
#        Window options         #
#################################
# Списки окон, для которых не будут применяться настройки
wintypes:
{
  tooltip = { fade = true; shadow = false; };
  dock = { shadow = false; };
  dnd = { shadow = false; };
};

#################################
#          Transparency         #
#################################
# Применить прозрачность к неактивным окнам
inactive-opacity = 1.0;
# Применить прозрачность к активным окнам
active-opacity = 1.0;
# Скрыть обводку прозрачности
detect-client-opacity = true;

#################################
#        Backends               #
#################################
# Выбор бэкенда. Наиболее стабильный на Xorg - "xrender"
backend = "xrender";

#################################
#          General              #
#################################
# Включить/выключить Picom
backend = "glx";
vsync = true;

